### PR TITLE
Negation overflow in Fixed::div

### LINKED ISSUE #1652: Neg overflow in hinting identified by Oss Fuzz
See \
https://oss-fuzz.com/testcase-detail/5666843647082496
https://issues.oss-fuzz.com/issues/443104630

```
#18 0x57e5574c5af2 in skrifa::outline::glyf::hint::math::div::hd01f619fa880f24e [fontations/skrifa/src/outline/glyf/hint/math.rs:35](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/math.rs#L35):5
    #19 0x57e5574c8f78 in skrifa::outline::glyf::hint::zone::Zone::iup_interpolate::h88b931887da0995e [fontations/skrifa/src/outline/glyf/hint/zone.rs:310](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/zone.rs#L310):33
    #20 0x57e557497f0c in skrifa::outline::glyf::hint::zone::Zone::iup::hef5452e18d0f983f [fontations/skrifa/src/outline/glyf/hint/zone.rs:179](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/zone.rs#L179):25
    #21 0x57e557497f0c in skrifa::outline::glyf::hint::engine::outline::_$LT$impl$u20$skrifa..outline..glyf..hint..engine..Engine$GT$::op_iup::he33baa81088ec224 [fontations/skrifa/src/outline/glyf/hint/engine/outline.rs:796](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/engine/outline.rs#L796):13
    #22 0x57e557497f0c in skrifa::outline::glyf::hint::engine::dispatch::_$LT$impl$u20$skrifa..outline..glyf..hint..engine..Engine$GT$::dispatch_inner::h2d14fd93196fd8f2 [fontations/skrifa/src/outline/glyf/hint/engine/dispatch.rs:142](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/engine/dispatch.rs#L142):28
    #23 0x57e557497f0c in skrifa::outline::glyf::hint::engine::dispatch::_$LT$impl$u20$skrifa..outline..glyf..hint..engine..Engine$GT$::dispatch::h470b7692070941fc [fontations/skrifa/src/outline/glyf/hint/engine/dispatch.rs:89](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/engine/dispatch.rs#L89):9
    #24 0x57e557497f0c in skrifa::outline::glyf::hint::engine::dispatch::_$LT$impl$u20$skrifa..outline..glyf..hint..engine..Engine$GT$::run::h60d94f157402a3cc [fontations/skrifa/src/outline/glyf/hint/engine/dispatch.rs:59](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/engine/dispatch.rs#L59):13
    #25 0x57e5574c4606 in skrifa::outline::glyf::hint::instance::HintInstance::hint::h89e8d687532c23fc [fontations/skrifa/src/outline/glyf/hint/instance.rs:160](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/hint/instance.rs#L160):9
    #26 0x57e5574dac5b in _$LT$skrifa..outline..glyf..FreeTypeScaler$u20$as$u20$skrifa..outline..glyf..Scaler$GT$::load_simple::h6a41cb4c7111feea [fontations/skrifa/src/outline/glyf/mod.rs:721](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/mod.rs#L721):32
    #27 0x57e5574d57be in skrifa::outline::glyf::FreeTypeScaler::scale::hdf8a59283f06849e [fontations/skrifa/src/outline/glyf/mod.rs:467](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/glyf/mod.rs#L467):9
    #28 0x57e5573923e7 in skrifa::outline::hint::HintingInstance::draw::_$u7b$$u7b$closure$u7d$$u7d$::h4d3fd2a9c2d7eac0 [fontations/skrifa/src/outline/hint.rs:430](https://github.com/googlefonts/fontations/blob/7656554cbfcedff46dcededea17daf5f38e1de63/skrifa/src/outline/hint.rs#L430):42
```

### PR DESCRIPTION
**Pull request by dfrg**
See
https://oss-fuzz.com/testcase-detail/5666843647082496 https://issues.oss-fuzz.com/issues/443104630

Applies a similar patch to Fixed::mul_div for good measure. First commit contains failing tests.

Fixes #1652

### CODE REVIEW

**Review by drott — APPROVED** [review]
LGTM, but perhaps @cmyr should take a look, too?

File: font-types/src/fixed.rs [hunk 1]
```diff
@@ -168,7 +168,7 @@ macro_rules! fixed_mul_div {
                     0x7FFFFFFF
                 };
                 Self(if sign < 0 {
-                    -(result as i32)
+                    (result as i32).wrapping_neg()
```
Comment (cmyr) [inline font-types/src/fixed.rs:171]: I propose we leave this crash in, just as an easter egg

Comment (dfrg) [reply font-types/src/fixed.rs:171]: but we undoubtedly have so many easter eggs still to find!
