### PR TITLE
Fix arg order in TableProvider::hmtx

### LINKED ISSUE #105: otexplorer throws `hmtx: Error 'An offset was out of bounds'` with NotoColorEmoji
get the font from https://github.com/googlefonts/noto-emoji/blob/main/fonts/Noto-COLRv1.ttf

then try use otexplorer to dump the hmtx table and observe this unexpected error:

```
$ cargo run --bin otexplorer -- -t hmtx ../noto-emoji/fonts/Noto-COLRv1.ttf
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/otexplorer -t hmtx ../noto-emoji/fonts/Noto-COLRv1.ttf`
hmtx: Error 'An offset was out of bounds'
```

### PR DESCRIPTION
**Pull request by cmyr**
fixes #105

### CODE REVIEW

**Comment by rsheeter** [comment]
Typically for a bug fix I like to see a test that exposes the bug and is fixed by the change, should be feasible here I think?

**Review by rsheeter — APPROVED** [review]
LGTM subject to adding a test

File: read-fonts/src/table_provider.rs [hunk 1]
```diff
@@ -101,3 +101,56 @@ pub trait TableProvider<'a> {
...
+    /// https://github.com/googlefonts/fontations/issues/105
+    #[test]
+    fn bug_105() {
+        // serve some dummy versions of the tables used to compute hmtx. The only
+        // fields that matter are maxp::num_glyphs and hhea::number_of_h_metrics,
+        // everything else is zero'd out
+        struct DummyProvider;
+        impl TableProvider<'static> for DummyProvider {
+            fn data_for_tag(&self, tag: Tag) -> Option<FontData<'static>> {
+                if tag == Tag::new(b"maxp") {
```
Comment (anthrotype) [inline read-fonts/src/table_provider.rs:119]: beginner question: would it not be more "idiomatic" to write this if/else block as a match statement?

Comment (cmyr) [reply read-fonts/src/table_provider.rs:119]: It would, but unfortunately `match` does not allow us to have a 'method call' in a pattern, even if it is a `const` method, so we can't match against `Tag::new(b"xxxx")`, and would need to have `if` guards anyway, like:

```rust
match tag {
    t if t == Tag::new(b"maxp") => (),
   // etc
}
```

which I wouldn't hate, but it doesn't feel like exactly a match statement? it is a bit more concise though..

Comment (anthrotype) [reply read-fonts/src/table_provider.rs:119]: oh i see. thanks for the explanation!
