### PR TITLE
[skrifa] glyf: use gvar for advance delta when HVAR is missing

### LINKED ISSUE #1311: Incorrect hinted advance for variable font with CVT variable hinting input values
With https://github.com/googlefonts/fontations/commit/8ecb5cdad8b8a454eb3e7879aac3597965c93776#diff-85acbbaaf5a080a3fd6ce893ff793469f3a30eea839ca12dc7d1b61d2972f984R1414

and testcase `fn vara_hinted_advances()`

observe that hinted advance and `GlyphMetrics` advance differ widely, resulting in a compressed and incorrect display (see *diff:* field of output).

The hinted advances seem to suit the default instance of the font at `wdth: 50`, but not the `wdth: 100` instance. 

Image

```
---- outline::tests::vara_hinted_advances stdout ----
Gid: 1, font size: 120.0 adjusted hinted advance: Some(31.0) vs. adjusted unhinted: Some(30.953125), glyph metrics advance: Some(30.959976) - diff: 0.040023804
Gid: 19, font size: 120.0 adjusted hinted advance: Some(42.0) vs. adjusted unhinted: Some(41.765625), glyph metrics advance: Some(71.75993) - diff: -29.759933
Gid: 83, font size: 120.0 adjusted hinted advance: Some(40.0) vs. adjusted unhinted: Some(40.203125), glyph metrics advance: Some(70.55994) - diff: -30.559937
Gid: 113, font size: 120.0 adjusted hinted advance: Some(27.0) vs. adjusted unhinted: Some(27.234375), glyph metrics advance: Some(39.59996) - diff: -12.59996
Gid: 110, font size: 120.0 adjusted hinted advance: Some(42.0) vs. adjusted unhinted: Some(42.234375), glyph metrics advance: Some(68.63994) - diff: -26.639938
Gid: 119, font size: 120.0 adjusted hinted advance: Some(34.0) vs. adjusted unhinted: Some(34.3125), glyph metrics advance: Some(58.679947) - diff: -24.679947
```

### PR DESCRIPTION
**Pull request by dfrg**
We were using gvar to compute deltas for left side-bearings but not for advance widths when the HVAR table is missing.

This only affects the TrueType interpreter (for Skia's usage) and hinted VFs are rare so it took a while to catch this one.

Fixes #1311

### CODE REVIEW

**Review by cmyr — APPROVED** [review]
looks good, tricky little one...

File: skrifa/src/outline/glyf/deltas.rs [hunk 1]
```diff
@@ -73,13 +83,15 @@ where
...
-        points.len() - 3
+    // Determine which phantom points to modify based on the presence and
+    // content of the HVAR table.
+    let actual_len = match var_metrics {
+        // Modify LSB and advance
+        AvailableVarMetrics::Missing => points.len() - 2,
+        // Modify only LSB
+        AvailableVarMetrics::MissingSideBearings => points.len() - 3,
+        // Modify nothing
+        AvailableVarMetrics::Present => points.len() - 4,
```
[the remark this answers is not in the document]
Comment (dfrg) [reply skrifa/src/outline/glyf/deltas.rs:94]: yeah, we ensure at least 4 points at entry to the function:
https://github.com/googlefonts/fontations/blob/7ecd4d178ff948ac2a55bb77714d8642003450d5/skrifa/src/outline/glyf/deltas.rs#L71

[the remark this answers is not in the document]
Comment (rsheeter) [reply skrifa/src/outline/glyf/deltas.rs:94]: Why isn't it written as `len - PHANTOM_POINT_COUNT`?

File: skrifa/src/outline/glyf/deltas.rs [hunk 2]
```diff
@@ -11,11 +11,21 @@ use read_fonts::{
...
 
+#[derive(Copy, Clone, Debug)]
+pub(super) enum AvailableVarMetrics {
+    /// Full variable metrics with advances and side-bearings.
+    Present,
+    /// Variable advances but not side-bearings.
+    MissingSideBearings,
+    /// No variable metrics table.
+    Missing,
+}
```
Comment (rsheeter) [inline skrifa/src/outline/glyf/deltas.rs:22]: I think I would expect these to be named for what *is* available not what isn't? - e.g. All, Advances, None as opposed to Present/MissingSide/Missing

File: skrifa/src/outline/glyf/mod.rs [hunk 3]
```diff
@@ -62,11 +63,16 @@ impl<'a> Outlines<'a> {
...
+        let var_metrics = match glyph_metrics.hvar.as_ref() {
+            Some(hvar) => {
+                if hvar.lsb_mapping().is_some() {
+                    AvailableVarMetrics::Present
+                } else {
+                    AvailableVarMetrics::MissingSideBearings
+                }
+            }
+            None => AvailableVarMetrics::Missing,
+        };
```
Comment (rsheeter) [inline skrifa/src/outline/glyf/mod.rs:75]: IMHO this might still read better (closer to left-to-right top to bottom) as map? - something like `glyph_metrics.hvar.map(|hvar| hvar.lsb_mapping.map(present).unwrap_or(missing sides)).unwrap_or(missing everything)`

File: skrifa/src/outline/glyf/mod.rs [hunk 4]
```diff
@@ -1159,10 +1171,16 @@ impl Scaler for HarfBuzzScaler<'_> {
...
-                    self.phantom[0].x += deltas[count - 4].x;
+                // Apply selective deltas to phantom points.
+                match self.outlines.var_metrics {
+                    AvailableVarMetrics::Missing => {
+                        self.phantom[0].x += deltas[count - 4].x;
+                        self.phantom[1].x += deltas[count - 3].x;
+                    }
+                    AvailableVarMetrics::MissingSideBearings => {
+                        self.phantom[0].x += deltas[count - 4].x;
+                    }
```
Comment (rsheeter) [inline skrifa/src/outline/glyf/mod.rs:1182]: Reading deltas at `count - magic #` is recurring, I wonder if there is an opportunity to make a helper fn or newtype with a nicely named (and probably always inlined) accessor?

**Comment by dfrg** [comment]
@rsheeter sure, will do a follow up with some of these changes
