### PR TITLE
[read-fonts] avoid overflow in midpoint computation

### LINKED ISSUE #1279: Add overflow in contour path extraction, reported by fuzzer
Spun off from:
https://issues.oss-fuzz.com/issues/382732980

Interesting part of stack trace:

```
#15 0x562cf15b2c82 in core::panicking::panic_fmt::h43c6bf7b4f5c72c3 /rustc/5315cbe15b79533f380bbb6685aa5480d5ff4ef5/library/core/src/panicking.rs:74:14
    #16 0x562cf15b3516 in core::panicking::panic_const::panic_const_add_overflow::hcdf3472a16af79c6 /rustc/5315cbe15b79533f380bbb6685aa5480d5ff4ef5/library/core/src/panicking.rs:181:21
    #17 0x562cf16f9667 in skrifa::outline::path::contour_to_path::h854d46b840da9c41 [fontations/skrifa/src/outline/path.rs:0](https://github.com/googlefonts/fontations/blob/a5bc98f8f3af8fbaaa12ae5f32228cdc684e676e/skrifa/src/outline/path.rs#L0)
    #18 0x562cf16fc57e in skrifa::outline::path::to_path::h9a8d9f122054ad00 [fontations/skrifa/src/outline/path.rs:92](https://github.com/googlefonts/fontations/blob/a5bc98f8f3af8fbaaa12ae5f32228cdc684e676e/skrifa/src/outline/path.rs#L92):9
    #19 0x562cf16f58ed in skrifa::outline::glyf::outline::ScaledOutline$LT$C$GT$::to_path::hba829ffbf6e6d9bb [fontations/skrifa/src/outline/glyf/outline.rs:158](https://github.com/googlefonts/fontations/blob/a5bc98f8f3af8fbaaa12ae5f32228cdc684e676e/skrifa/src/outline/glyf/outline.rs#L158):9
    #20 0x562cf16f58ed in skrifa::outline::hint::HintingInstance::draw::_$u7b$$u7b$closure$u7d$$u7d$::h3c382027f6b258c9 [fontations/skrifa/src/outline/hint.rs:430](https://github.com/googlefonts/fontations/blob/a5bc98f8f3af8fbaaa12ae5f32228cdc684e676e/skrifa/src/outline/hint.rs#L430):36
```

### PR DESCRIPTION
**Pull request by dfrg**
Fixes #1279

ref https://issues.oss-fuzz.com/issues/382732980

### CODE REVIEW

File: read-fonts/src/tables/glyf.rs [hunk 1]
```diff
@@ -798,10 +798,19 @@ impl PointCoord for i32 {
...
+        midpoint_i32(self, other)
     }
 }
 
+// Midpoint function that avoids overflow on large values.
+fn midpoint_i32(a: i32, b: i32) -> i32 {
+    // Original overflowing code was: (a + b) / 2
+    // Choose wrapping arithmetic here because we shouldn't ever
+    // hit this outside of fuzzing or broken fonts _and_ this is
+    // called from very performance sensitive code
```
Comment (rsheeter) [inline read-fonts/src/tables/glyf.rs:810]: This is a good comment. It would be great if it said what specific performance sensitive code.

**Review by rsheeter — APPROVED** [review]
