### PR TITLE
[read-fonts] Avoid overflow in matrix degeneracy check

### LINKED ISSUE #1595: Chrome runs into MulOverflow with CFF font and FontMatrix parsing
After the font matrix skew fixes for #1581 , when trying to roll Fontations into Chrome, I now occasionally (no local repro) yet multiplication overflow panics. 

Font ExTest.woff shows:
```
      <FontMatrix value="0.000976562 0 0 0.000976562 0 0"/>
```

Example stack trace excerpt:

```
[...]
#16 0x5d23890a2d0d core::panicking::panic_fmt::h84281f2a9db3f733
#17 0x5d23891122a8 core::panicking::panic_const::panic_const_mul_overflow::h5fbcd1b58a0768d3
#18 0x5d23891915ae read_fonts::tables::postscript::dict::parse_font_matrix::h79e4c29ec9f82cf5
#19 0x5d23891eb580 read_fonts::tables::postscript::dict::entries::_$u7b$$u7b$closure$u7d$$u7d$::h4b7c9647d7f37817
#20 0x5d23891ee585 skrifa::outline::cff::TopDict::new::h9a8671d832434a08
[...]
```

[extest_woff.zip](https://github.com/user-attachments/files/21715475/extest_woff.zip)

### PR DESCRIPTION
**Pull request by dfrg**
Fixes #1595

### CODE REVIEW

File: read-fonts/src/tables/postscript/dict.rs [hunk 1]
```diff
@@ -561,12 +561,23 @@ fn parse_font_matrix(cursor: &mut Cursor) -> Option<([Fixed; 6], i32)> {
...
 /// See <https://gitlab.freedesktop.org/freetype/freetype/-/blob/f1cd6dbfa0c98f352b698448f40ac27e8fb3832e/src/base/ftcalc.c#L725>
 fn is_degenerate(matrix: &[Fixed; 6]) -> bool {
-    // Convert to i64 to avoid overflows below
-    let [xx, yx, xy, yy, ..] = matrix.map(|x| x.to_bits() as i64);
+    let [mut xx, mut yx, mut xy, mut yy, ..] = matrix.map(|x| x.to_bits() as i64);
     let val = xx.abs() | yx.abs() | xy.abs() | yy.abs();
+    if val == 0 || val > 0x7FFFFFFF {
+        return true;
+    }
+    // Scale the matrix to avoid temp1 overflow
```
Comment (drott) [inline read-fonts/src/tables/postscript/dict.rs:569]: I can't say whether this is a common approach for the `is_degenerate`, but LGTM. 

I briefly looked at
https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/src/core/SkMatrix.cpp;l=176?q=skmatrix.cpp - but I guess nothing prevents this from overflowing, too.

Comment (dfrg) [reply read-fonts/src/tables/postscript/dict.rs:569]: For better or worse, it's exactly what FreeType does 🤷
