### PR TITLE
[skrifa] autohint: use visited set when processing GSUB lookups

### LINKED ISSUE #1363: Autohinting of Noto Nastaliq 3.007 hangs in GSUB processing
Spun off from:
https://issues.chromium.org/396173460

Hanging in a stack like below, for glyph sequence:
`13,235,33,966,305,255,966,304,11,233,29,218,3,233,243,218,3,1266,227,580,15,371,1266,966,277`

Font from test in bug report:
[noto_nastaliq.zip](https://github.com/user-attachments/files/18910770/noto_nastaliq.zip)

Stack:

```
#0  0x000055555753b79f in font_types::raw::{impl#21}::from_raw (raw=...) at external/fontations__font-types-0.8.3/src/raw.rs:191
#1  core::ops::function::FnOnce::call_once<fn([u8; 2]) -> u16, ([u8; 2])> () at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250
#2  0x0000555557516549 in core::option::Option<[u8; 2]>::map<[u8; 2], u16, fn([u8; 2]) -> u16> (self=..., f=0x555557642ec000)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1072
#3  0x0000555557642ec0 in font_types::raw::Scalar::read<u16> (slice=...) at external/fontations__font-types-0.8.3/src/raw.rs:24
#4  0x00005555575370bf in core::ops::function::FnOnce::call_once<fn(&[u8]) -> core::option::Option<u16>, (&[u8])> ()
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250
#5  0x000055555752246c in core::option::Option<&[u8]>::and_then<&[u8], u16, fn(&[u8]) -> core::option::Option<u16>> (self=..., f=0x7ffff41201f200)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1406
#6  0x0000555557600a9b in read_fonts::font_data::FontData::read_at<u16> (self=0x7ffffffec178, offset=0) at external/fontations__read-fonts-0.27.1/src/font_data.rs:83
#7  0x000055555760b189 in read_fonts::font_data::Cursor::read<u16> (self=0x7ffffffec178) at external/fontations__read-fonts-0.27.1/src/font_data.rs:219
#8  0x00005555574a460b in read_fonts::tables::gsub::{impl#43}::read (data=...) at external/fontations__read-fonts-0.27.1/src/tables/../../generated/generated_gsub.rs:726
#9  0x000055555745f4b1 in read_fonts::read::{impl#1}::read_with_args<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>> (data=...)
    at external/fontations__read-fonts-0.27.1/src/read.rs:60
#10 0x0000555557622fa0 in read_fonts::offset::{impl#1}::resolve_with_args::{closure#1}<font_types::offset::Offset16, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>> (data=...) at external/fontations__read-fonts-0.27.1/src/offset.rs:94
#11 0x00005555574fa5f4 in core::result::Result<read_fonts::font_data::FontData, read_fonts::read::ReadError>::and_then<read_fonts::font_data::FontData, read_fonts::read::ReadError, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, read_fonts::offset::{impl#1}::resolve_with_args::{closure_env#1}<font_types::offset::Offset16, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>>> (self=..., op=...)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1316
#12 0x000055555756ac45 in read_fonts::offset::{impl#1}::resolve_with_args<font_types::offset::Offset16, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>> (self=0x7ffffffec41e, data=..., args=0x7ffffffed260) at external/fontations__read-fonts-0.27.1/src/offset.rs:91
#13 0x0000555557649bab in read_fonts::offset_array::{impl#1}::iter::{closure#0}::{closure#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16> (off=0x7ffff4119152) at external/fontations__read-fonts-0.27.1/src/offset_array.rs:85
#14 0x000055555751a2e2 in core::option::Option<&font_types::raw::BigEndian<font_types::offset::Offset16>>::map<&font_types::raw::BigEndian<font_types::offset::Offset16>, core::result::Result<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, read_fonts::read::ReadError>, read_fonts::offset_array::{impl#1}::iter::{closure#0}::{closure_env#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16>> (self=..., f=...)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1072
#15 0x0000555557649828 in read_fonts::offset_array::{impl#1}::iter::{closure#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16> () at external/fontations__read-fonts-0.27.1/src/offset_array.rs:84
#16 0x000055555767d5d7 in core::iter::sources::from_fn::{impl#0}::next<core::result::Result<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, read_fonts::read::ReadError>, read_fonts::offset_array::{impl#1}::iter::{closure_env#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16>> (self=0x7ffffffed240) at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/sources/from_fn.rs:69
#17 0x0000555557361afc in core::iter::traits::iterator::Iterator::try_fold<core::iter::sources::from_fn::FromFn<read_fonts::offset_array::{impl#1}::iter::{closure_env#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16>>, (), core::iter::traits::iterator::Iterator::find_map::check::{closure_env#0}<core::result::Result<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, read_fonts::read::ReadError>, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, &mut skrifa::outline::autohint::shape::{impl#2}::process_lookup_inner::{closure_env#3}>, core::ops::control_flow::ControlFlow--Type <RET> for more, q to quit, c to continue without paging--
<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, ()>> (self=0x7ffffffed240, init=(), f=...)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2461
#18 0x00005555573603bc in core::iter::traits::iterator::Iterator::find_map<core::iter::sources::from_fn::FromFn<read_fonts::offset_array::{impl#1}::iter::{closure_env#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16>>, read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, &mut skrifa::outline::autohint::shape::{impl#2}::process_lookup_inner::{closure_env#3}> (self=0x7ffffffed240, f=0x7ffffffed260)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2964
#19 0x0000555557451e7e in core::iter::adapters::filter_map::{impl#2}::next<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, core::iter::sources::from_fn::FromFn<read_fonts::offset_array::{impl#1}::iter::{closure_env#0}<read_fonts::table_ref::TableRef<read_fonts::tables::gsub::SequenceMarker>, font_types::offset::Offset16>>, skrifa::outline::autohint::shape::{impl#2}::process_lookup_inner::{closure_env#3}> (self=0x7ffffffed240)
    at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/adapters/filter_map.rs:63
#20 0x00005555573cf0dc in skrifa::outline::autohint::shape::GsubHandler::process_lookup_inner (self=0x7fffffff9f30, lookup_index=141)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:489
#21 skrifa::outline::autohint::shape::GsubHandler::process_lookup (self=0x7fffffff9f30, lookup_index=141)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:439
#22 0x00005555573cfe8a in skrifa::outline::autohint::shape::GsubHandler::process_lookup_inner (self=0x7fffffff9f30, lookup_index=142)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:551
#23 skrifa::outline::autohint::shape::GsubHandler::process_lookup (self=0x7fffffff9f30, lookup_index=142)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:439
#24 0x00005555573cfe8a in skrifa::outline::autohint::shape::GsubHandler::process_lookup_inner (self=0x7fffffff9f30, lookup_index=143)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:551
#25 skrifa::outline::autohint::shape::GsubHandler::process_lookup (self=0x7fffffff9f30, lookup_index=143)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:439
#26 0x00005555573cfde9 in skrifa::outline::autohint::shape::GsubHandler::process_lookup_inner (self=0x7fffffff9f30, lookup_index=144)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:544
#27 skrifa::outline::autohint::shape::GsubHandler::process_lookup (self=0x7fffffff9f30, lookup_index=144)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:439
#28 0x00005555573cfde9 in skrifa::outline::autohint::shape::GsubHandler::process_lookup_inner (self=0x7fffffff9f30, lookup_index=145)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:544
#29 skrifa::outline::autohint::shape::GsubHandler::process_lookup (self=0x7fffffff9f30, lookup_index=145)
    at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:439
#30 0x00005555573cd7b1 in skrifa::outline::autohint::shape::Shaper::compute_coverage (self=0x7fffffffaac0, style=0x555558e87008, 
    coverage_kind=skrifa::outline::autohint::shape::ShaperCoverageKind::Script, glyph_styles=...) at external/fontations__skrifa-0.28.0/src/outline/autohint/shape.rs:227
```

### PR DESCRIPTION
**Pull request by dfrg**
Adds a visited set to GSUB traversal for autohinting to prevent redundant processing of lookups. This can cause a perceived hang on fonts with large complex lookup graphs (like Noto Nastaliq Urdu) even when there are no cycles.

Also removes the existing cycle detection code since it is no longer needed.

Fixes #1363

### CODE REVIEW

File: skrifa/src/outline/memory.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+//! Support for temporary memory allocation, making use of the stack for
+//! small sizes.
+
+/// Invokes the callback with a memory buffer of the requested size.
+pub(super) fn with_temporary_memory<R>(size: usize, mut f: impl FnMut(&mut [u8]) -> R) -> R {
+    // Wrap in a function and prevent inlining to avoid stack allocation
+    // and zeroing if we don't take this code path.
```
Comment (cmyr) [inline skrifa/src/outline/memory.rs:7]: as in dead code analysis would not prune the branch if it was inlined? Is this a common trick?

**Review by cmyr — APPROVED** [review]
One question inline, looks like a sane approach.

File: skrifa/src/outline/memory.rs (hunk 1 above)
Comment (dfrg) [reply skrifa/src/outline/memory.rs:7]: yeah, this just guarantees that we'll never end up with a stack frame that is the sum of all potential buffer sizes. LLVM would _probably_ do a dynamic stack adjustment (`alloca` style) for each branch but you never know...
